export const ENDPOINTS = Object.freeze({
  AUTH: {
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forget-password",
    SIGNIN: "/signin",
    SIGNIN_SUCCESS: "/signin-success",
  },
  INDEX: "/",
  USER: {
    DASHBOARD: "/user/dashboard",
    DEMO: "/user/demo/:id",
    ADMINCOURSE: "/admin/course/:id",
    // DEMO: (id) => `/user/demo/${id}`,
    OOPS: "/user/oops",
    MANAMENT: "/admin/manament",
    NOTEST: "/user/notest",
    PAYMENT: "/user/payment",
    CER: "/user/cer",
    FLASHCARD: "/user/flashcard",
    COURSES: "/user/courses",
    COURSE: "/user/course",
    PREMIUM: "/user/premium",
    SAMPLETEST: "/user/sample-test",
    ADMINDASHBOARD: "/admin/dashboard",
    USERDASHBOARD: "/user/dashboard",
    LABS: "/user/labs",
    CFT: "/user/cft",
    CHATBOT: "/user/chatbot",
    // COURSES: "/user/courses",
    ABOUT: "/user/about",
    ADMINLAB: "/admin/lab-admin",
    ADMINCTF: "/admin/ctf-admin",
    ADMINPAYMENT: "/admin/payment-admin",
    CTFDETAIL: "/ctf/:id",
    LABDETAIL: "/labs/:id",
    PAYMENTSUCCESS: "/payment/return",
    PROFILE: "/user/profile",
    PACKAGES: "/user/packages",
  },
});
